name: Deploy React Application

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest

      - name: Delete old container (if exists)
        run: |
          docker stop reactjs-app-container || true
          docker rm reactjs-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
