name: Deploy React Application

on:
  push:
    branches:
      - mern-ec2-docker

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Image from Docker Hub
        run: docker pull akshx09/todo-frontend:latest

      - name: Delete Old Container
        run: docker rm -f reactjs-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container akshx09/todo-frontend:latest
