name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
     
      # Skip the build part since the image is already built
      # - name: Build Docker Image
      #   run: sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}' .

      - name: Publish Image to Docker Hub
        run: sudo docker push ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest 

      - name: Delete Old Container
        run: sudo docker rm -f todo-frontend-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 3000:80 --name todo-frontend-container ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
