name: Deploy React Application

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest

      - name: Stop and Remove old Frontend Container
        run: |
          docker stop reactjs-app-container || true
          docker rm reactjs-app-container || true

      - name: Stop and Remove old Backend Container
        run: |
          docker stop backend-container || true
          docker rm backend-container || true

      - name: Run Frontend Container
        run: docker run -d -p 4000:80 --name reactjs-app-container ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest

      - name: Run Backend Container
        run: docker run -d -p 3001:3000 --name backend-container ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
